ekisu/mpv-webm

Makefile, build/webm.lua, src/backends/base.moon, src/backends/ffmpeg.moon, src/backends/mpv.moon, src/encode.moon, src/encoding_parameters.moon, src/formats/base.moon, src/formats/rawvideo.moon, src/formats/webm.moon, src/options.moon, src/util.moon, src/video_to_screen.moon
Hey, for personal reasons I wanted to be able to use ffmpeg with this script, so I changed the way encoding is done a bit. This ended up being more massive than I thought, so I figured I'd open this pull request if you're interested, but I understand if it's out of scope.
Outline of changes:
- [`encode.moon`](https://github.com/sides/mpv-webm/blob/master/src/encode.moon) now doesn't build a command to be executed, but instead builds an instance of [`EncodingParameters`](https://github.com/sides/mpv-webm/blob/master/src/encoding_parameters.moon) which are passed to a backend (mpv or ffmpeg).
- [`webm.moon`, `rawvideo.moon`, `formats/base.moon`](https://github.com/sides/mpv-webm/tree/master/src/formats):
- Now receive a backend instance in their `getX` methods.
- No longer return raw …
=> ffmpeg support

build/webm.lua, src/util.moon
On Windows, io.open fails with UTF-8 (and possibly any non-system-conforming) encodings. It seems `utils.file_info` already handles this so we're good.
Fixes #43.
=> file_exists: use utils.file_info() instead of io.open()

Makefile, build/webm.lua, src/base64.lua, src/encode.moon, src/util.moon, src/vp8_twopass_log_patcher.moon
The pass log file generated by mpv doesn't contain the correct duration of each frame/aggregated sum, which leads to garbage encodes when used on the second pass.
Workaround this by writing the average frame duration on the frame stats, and the total encode duration on the EOS packet. This should be fairly accurate when dealing with constant frame rate videos, which, hopefully, is the most common case.
Closes #6 (after only two years :^)).
=> encode: patch libvpx 2-pass log file

build/webm.lua, src/EncodeWithProgress.moon
It seems that recent versions of mpv stopped emitting newlines on `term-status-msg`, unless explicitly told to do so. Should fix #73.
=> EncodeWithProgress: emit \n on term-status-msg

Makefile, build/webm.lua, src/EncodeOptionsPage.moon, src/encode.moon, src/formats/base.moon, src/formats/mp3.moon
~~hope this doesn't break everything~~
Adds support for formats with only audio codecs. Essentially, just added some guards around video flags (which is what most of the logic of the script is around), and changed how bitrate is calculated to accomodate to this change (there's not always a video track, after all).
Closes #85
=> encode, formats: add support for audio only formats

build/webm.lua, src/options.lua, src/util.moon
Continuation of the work in #92 
The original PR would use the first fallback value for all properties of the same name, e.g. `%{someproperty:fallbackone} %{otherproperty:fallbacktwo} %{someproperty:fallbackthree}` would result in `fallbackone fallbacktwo fallbackone`. This is fixed.
This supports recursive expansion and comparisons like `%{?video-frame-info/picture-type==I:keyframe${estimated-frame-number:X}}`.
Didn't use `expand-text` as it doesn't support `%{}` and because of other annoyances I touch on later.
It has the same limitations as `--screenshot-template`, a closing curly bracket will close all previous curly brackets, regardless of nesting.
This means that instead of `%{!fps==22:${height}p}` you have to write `%{!fps==22:${height}}%{!fps==22:p}`.
If mpv logic ever changes to …
=> Recursive expansion in output template

build/webm.lua, src/encode.moon
Some releases require `--sub-ass-vsfilter-aspect-compat=no` to display properly.
This change reflects its current value in the output video.
There are other properties that one may want to keep, open to discussion about that before merge.
=> Respect vsfilter aspect ratio setting

Makefile, build/webm.lua, src/EncodeOptionsPage.moon, src/formats/gif.moon, src/util.moon
Hi!
I wanted to add gif support and it looked simple enough. I added an extra `hasAudioCodec` check for the `-audio` text in filename generation in `util.moon` as gif is video only.
=> Add gif encoding support

build/webm.lua, src/encode.moon
Thanks to @Igetin for the implementation (I really didn't know `dump-cache` was a thing). For now I'll keep it only on HLS streams, as I guess other ones might work with the original implementation (?). Might change this later tho. The code for this became a bit ugly too, but eh
~~return nil, nil, nil, nil, nil isn't supposed to be a joke too~~
Closes #28
=> Add support for encoding HLS livestreams

build/webm.lua, src/formats/webm.moon, src/options.lua
Opus is already used by YouTube and supported by default on just about
every distribution's build of mpv/ffmpeg. It gets much better
compression ratios without a loss in quality
=> Switch from vorbis audio to opus audio

src/options.lua
Just a small comment change for people who use a config file so they don't have to look through the source to see all available formats
=> Add all supported formats to comment

src/encode.moon
I've been using mpv-webm with some interlaced videos, and I've noticed the output has interlacing artifacts. I've added the `deinterlace` property to the playback options so that its current state is passed.
=> Add deinterlace property to playback options

src/EncodeOptionsPage.moon, src/encode.moon, src/formats/base.moon, src/formats/gif.moon, src/options.lua
Hi,
This is my attempt to address #111 
To generate higher quality gifs this PR changes the gif format to use palettes. The `paletteuse` filter that achieves this requires complex filters to be used with `--lavfi-complex`, and this doesn't seem to play well with some other `--vf-add` options. The solution I came up with was to add a `postCommandModifier` method to the `Format` class that can alter the command line arguments. In the gif case it goes over the list and and tries to convert various options to their complex filter equivalents. I don't know if this is acceptable but I can try to change it if there's a better way.
I also added a new option to `options.lua` to change the dither flags to use for `palleteuse`.
Edit:
Fixed typo
=> Generate gifs with palletegen/paletteuse

src/EncodeOptionsPage.moon, src/encode.moon, src/options.lua
Hi,
I've noticed that newer versions of Firefox display some videos I create with the wrong aspect ratio. Digging a bit, it looks like it started having issues with webms with non-square pixels. This change adds another filter to convert the video to square pixels before doing scaling.
Seems like it's a known bug on Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1697316
Coincidentally, this also fixes #104 I think
=> Add 'Force Square Pixels' option

src/formats/webm.moon, src/options.lua, tests/mpv_ipc.py
Taken from the [VP8 Encode Parameter Guide](https://www.webmproject.org/docs/encoder-parameters/). Should improve mostly twopass only, so for now twopass is the default. ~~hopefully nothing breaks~~
=> Use better quality defaults

src/options.lua
Or maybe don't rename it so it doesn't break people's existing configs?
Either would be fine...
=> Update config comments to indicate 'mp4' formats have been renamed to 'avc'

src/MainPage.moon
This PR adds keys `!` (`shift+1`) and `@` (`shift+2`)  as bindings to jump to the start and end time of the excerpt, respectively.
This is useful when attempting to export a "perfect loop" for example, but they're also useful in general when refining the export region.
I'm not attached to `shift+1`/`shift+2` as keybindings, so if you think they should be changed to something else, I can change them. Or if you think they should show up in the OSD as `shift+1`/`shift+2` instead of `!` and `@`.
=> add bindings to jump to start/end times of the selected export region

src/util.moon
This commit adds options.target_filesize to the replace table for writing file names. This is a change I always add when updating webm.lua. This is added because different platforms have different file size upload limits, so I often encode the same clip at different file sizes. The file names are then differentiated by size so that they don't overwrite. I'm submitting a pull request for this so that I don't need to re-add this to the script every time I update it.
=> Add options.target_filesize to replace table

src/encode.moon
Most subtitle related mpv config options were not being passed in even when `apply_current_filters = true` was set, resulting in the encoded video always using default subtitle styling. 
I added the most common cosmetic subtitle options in a function similar to `get_playback_options`. These options get added as command line parameters to the mpv command.
Note that this makes the final mpv command rather verbose which you might find undesirable. I also have no idea if the fact MPV ignores these configuration options in encoding mode (`-o`) is intended behaviour or a bug...
This fixes #191 and is a possible solution for other subtitle related issues
=> Fix custom sub styling

src/encode.moon
The `sub-ass-vsfilter-aspect-compat` option has been removed from mpv. This change uses the new option.
=> Update deprecated sub option

src/encode.moon, src/options.lua
This PR adds an option `completion_command`, which, when set, will cause mpv-webm to run the specified mpv command when the encoding completes successfully.
The string `%{output}` will be replaced with the path to the output file.
This may be useful, for example, to automatically copy the path to the system clipboard, i.e.:
`completion_command=set "clipboard/text" "%{output}"`
(Note that `set "clipboard/text"` only works on Windows, Wayland, and macOS).
Alternatively, if you have a script that copies its arguments to the clipboard (as I do, since I use X11):
`completion_command=run "script-for-copying-args-to-clipboard" "%{output}"`
(Unfortunately, `xclip` and `xsel` don't seem to have the ability to copy from arguments, and I'd rather not invoke a subshell if possible just for piping to …
=> Add option to run mpv command on successful encode
